### PR TITLE
[impl] Port fs modules to kernel version > 4.4

### LINKED ISSUE #65: Update vfat and ext2fs implementations to build/run against the latest kernel
Our implementation of both `ext2` and `vfat` in Cogent is a little dated, and we need to update it to build against the latest kernel implementation. 
Currently, it works against the patched 4.3 kernel in `Debian`, but doesn't build on the `Arch`'s kernel.

### PR DESCRIPTION
**Pull request by ajaysusarla**
This patch ports the Cogent fs modules `vfat` and `ext2` to support the
recent kernels(4.4 and later).

Unfortunately, there is a fair bit of redundant code, because of an
issue with the anit-quotation(`Language.C.Parser` and
`Language.C.Quote`), they (and hence Cogent) expects a statement in a
function to end with a ';' and that results in a warning about a stray
';' generated by the CPP. And hence the duplication.

This patch doesn't include port the bilby implementation, since it isn't
as straightforward. I'm working on that patch, and will send it soon.

I've also remove code to run on kernel version < 3.16, we don't support
them anymore.

Fixes #65.

### CODE REVIEW

**Comment by ajaysusarla** [comment]
@zilinc I have no idea how to solve the build issue with: https://travis-ci.org/NICTA/cogent/jobs/234670192, can you take a look at it when possible? I actually can get it to build on my Arch Linux box with `ghc 8.0.1`:
```
$ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
$ cogent --version
Cogent development version: 2.0.8.0-fdbd416ac2
```

**Comment by ajaysusarla** [comment]
@zilinc that fix was trivial, just had to bump the version of either. The CI seems to be happy, merge whenever you can. Thanks again.

**Comment by zilinc** [comment]
@ajaysusarla we now have the statement level counterpart of `$esc` (see the antiquotation doc file in `cogent/doc`) antiquoter but I don't find you use it. Is it going to help you?

**Comment by zilinc** [comment]
or see my comment in #65

**Comment by ajaysusarla** [comment]
@zilinc I did try to use `$esc` within a function, and unfortunately, I was still having trouble getting it to parse. The Compiler(parser) still complained that it exected '`;`' but got some statement instead.

**Comment by zilinc** [comment]
The stmt level one is `$escstm`, I think.

**Comment by ajaysusarla** [comment]
For instance, if I did something like this
```
$esc:(#if LINUX_VERSION_CODE < KERNEL_VERSION(4,4,0))
    if (can_truncate_res.p2.tag == TAG_ENUM_Error) {
        err = -((int)can_truncate_res.p2.Error);
    }
$esc:(else)
    if (can_truncate_res.p2.tag == TAG_ENUM_Error) {
        err = -((int)can_truncate_res.p2.Error);
    }
$esc:(endif)

```

The compiler throws this error, and bails:
```
Glue code (functions) generation failed: 
Error: Failed to parse C: plat/linux/wrapper_pp.ac:27326:5:
    expected ';' but got `if'
Compilation failed!
make: *** [Makefile:135: .c-gen] Error 134
```

**Comment by ajaysusarla** [comment]
`escstm` is it? I will check that, give me a tick.

**Comment by ajaysusarla** [comment]
@zilinc `$escstm` works. I shall send update the patch and let you know. Thanks for your time.

**Comment by ajaysusarla** [comment]
@zilinc The changes are made the CI is green. Please do merge when you can.

When possible(maybe next week or so), I shall do a lot more changes with regards the `$escstm`. I've noticed a whole lot of places in the code, where we could use that.

**Comment by zilinc** [comment]
subsumed by #99

**Pull request closed without merging**
