### PR TITLE
Examples

### PR DESCRIPTION
**Pull request by azreika**
These are some basic Cogent programs made as examples.

### CODE REVIEW

**Comment by liamoc** [comment]
Awesome! This will be very useful.

**Comment by ajaysusarla** [comment]
@zilinc I prefer that you review the pull request when you can. This is the first in the series of pull requests from @azreika. 
Merge, if you are happy with it.

**Comment by zilinc** [comment]
Suggestions for improvement:
* move the examples to `cogent/examples`
* @azreika I'd like to ask you to write comment on one example about:
  - how the Makefile works (namely why these compiler flags and the files you give to the compiler)
  - when you need which antiquoters for what. (your `$esc` on `printf` functions are not needed)
* TBA

**Comment by ajaysusarla** [comment]
@azreika @zilinc Regarding documentation of the `Makefile`, I should probably write that. @azreika If you want to try, go ahead, let me know if you want me to/need any information.

**Comment by zilinc** [comment]
Also I may need to make a verification target as well.

**Pull request merged**
